before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: Gjn2Nf6Msb8UByJeDocz3WZMS4eI5jS856QL8/GL9la4mMEc75UJX+I19jxmP8XUS1GW7Jj7LFptq5QLGSGvdQpoi8yQoeZbLV9NfPEeCLKm8MHQIPSfJ1gC/luQ8+6ZfSvO5z6YxqYQ6mSiaw4CgHC562tYyC4GXb7y/XwcxEwSBqRYlzmQffKDorG4DGLwPD16Q/NCTC7iRRGWLoHznfOsx2rdbHhwTuoGVxwaskfzmCwpac42Qs/YJpiEzl2nvIYD28sJ+VCIDStDl2In3VIT4eJNAoXBMh5Mjvf2nHeYMDzC/D/p5RTYisZZNcKryh29tyxfo7Enb5cmP1jXF2L/jwdxHQOIaSVdmTfx9i9zAVYg5GpuAy3Vnj3uEX3N4oc4nPEff11JV32FV/O2YsDBDFM6KRuYk55ucEs8erRemELmDWqNBlDckHaVC0mqAAHrfE6FNSFQIe32vfX1FQhg1JjKo1GerPCUlkzVbKTiqqdWQkPA6J2DSbeNpeGaXVueJIDpX+oEDAshtTXqKpUpkZ0lNBNe9RRQE9d4FK3e+SOQ/f044gD0NuQMjxilNgWt0e1K883s9g02EvL3Um2uM/BtVyaDC4qx1rNR5uJr3iIOgOP0Z47wmEF0K6UzoxnOxfEbFwXAhHfWzn/J3Ini6s6GqO7lUVTYA0g3Nmo= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
